### ISSUE TITLE
Behaviors are not destroyed correctly ?

### ISSUE THREAD

**Issue by m4n1ok** [area17/a17-behaviors#1]
It appears when using PJAX libraries that behaviors aren't destroy correctly.

After investigation, it looks like requested `bNodeActiveBehaviors` inside `destroyBehaviors` method return always an empty array.

**Comment by 13twelve** [comment]
Updated in `0.1.6`.

Issue was that `destroyBehaviors` was only looking at the removed node itself and not that node's children.

**Comment by m4n1ok** [comment]
Thank you @13twelve for the quick fix and for explanation too :)
