### ISSUE TITLE
When in dev how can I see JS errors inside a behavior?

### ISSUE THREAD

**Issue by mattbloomfield** [area17/a17-behaviors#2]
It's difficult to debug within a behavior. If there is a JS error it simply console logs "No loaded behavior called: xxxxxxx"

Is there a way to expose the errors?

**Comment by 13twelve** [comment]
New version `0.1.11` will console log out any errors when initialising a behavior (latest version is now `0.1.12`)

**Comment by mattbloomfield** [comment]
Oh nice, thanks

**Comment by mattbloomfield** [comment]
Just tried it out, great implementation! Very descriptive. Thank you Mike.
